### ISSUE TITLE
Header text sizing issue

### ISSUE THREAD

**Issue by OpenSZN39** [haywasta/web-design-2-independent-project#2]
Hey @haywasta  I know your still laying stuff out, but I noticed while checking out your site that on mobile sizes your nav in the header starts to lose itself a bit. 

![image](https://user-images.githubusercontent.com/77280572/145910322-f944741e-4dd0-4f5a-8cf2-71dd6795a42a.png)

You may want to look at adjusting how your logo and nav texts resize themselves when on smaller screens!

Cant wait to see the final site!

**Comment by haywasta** [comment]
Thank you for your feedback!
